#!/bin/bash
# PreToolUse hook: block edits to protected files
# Exit code 2 = hard block (Claude sees the message and cannot proceed)

input=$(cat)

# Parse tool_name and file_path in a single pass
parsed=$(echo "$input" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_name','')); print(d.get('tool_input',{}).get('file_path',''))" 2>/dev/null)
tool_name=$(echo "$parsed" | head -n 1)
file_path=$(echo "$parsed" | tail -n 1)

# Only check Edit and Write tools
if [[ "$tool_name" != "Edit" && "$tool_name" != "Write" ]]; then
  exit 0
fi

block_with_reason() {
  echo "BLOCKED: $file_path is a protected file."
  echo "Reason: $1"
  exit 2
}

# .env files (matches .env, .env.local, .env.development, etc.)
if [[ "$file_path" =~ (^|/)\.env(\.|$) ]]; then
  block_with_reason ".env files contain secrets and must never be modified by Claude. Edit them manually."
fi

case "$file_path" in
  */package-lock.json)
    block_with_reason "package-lock.json is managed by npm only. Run 'npm install' to update it."
    ;;
  */yarn.lock)
    block_with_reason "yarn.lock is managed by yarn only. Run 'yarn install' to update it."
    ;;
  */Gemfile.lock)
    block_with_reason "Gemfile.lock is managed by bundler only. Run 'bundle install' to update it."
    ;;
  */db/structure.sql)
    block_with_reason "db/structure.sql is auto-generated by Rails migrations. Run 'rails db:migrate' instead of editing it directly."
    ;;
esac

# Encrypted credentials and keys
if [[ "$file_path" == *"credentials.yml.enc" ]] || [[ "$file_path" == *".key" ]] || [[ "$file_path" == *"master.key" ]]; then
  block_with_reason "Encrypted credentials and key files must never be modified by Claude. Use 'rails credentials:edit' instead."
fi

exit 0
